[env:stickcplus2]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-5A6C0505221
monitor_port = /dev/cu.usbserial-5A6C0505221
lib_deps =
    m5stack/M5Unified@^0.1.16
    h2zero/NimBLE-Arduino@^1.4.2
    bblanchon/ArduinoJson@^7.0.0
